default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postgresql_development

test:
  <<: *default
  database: postgresql/test


#     url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: postgresql_production
  username: post
  password: <%= ENV['POST_DATABASE_PASSWORD'] %>
